### ISSUE TITLE
关于MD模型

### ISSUE THREAD

**Issue by Ultraman6** [youngfish42/FMTL-Benchmark#1] opened 2024-06-28 06:54 UTC
model/Decoder_noadain这个类中，所有任务的输出按通道concat成一个大的张量，但为什么最后输出只经过一个检测头？
![1e8ec127cf74e53cea6c4a39e94f880d](https://github.com/youngfish42/FMTL-Benchmark/assets/99520469/d2447e40-253d-4baa-b269-6e2c57a0ce02)
![d73071598c09825ce78a75b3f58a437a](https://github.com/youngfish42/FMTL-Benchmark/assets/99520469/be0002e7-b3c3-47cd-a10a-698c1f816def)
如果任务类型不同或者同类型任务输出维度不同那怎么办？

**Comment by innovator-zero** [comment] 2024-06-29 07:48
Hi, thank you for the question.
Yes, we use a single prediction head for all tasks. This head projects the feature to the maximum number of channels required among all tasks. Then an adaptive pooling operation is used to adjust the number of channels to meet the specific needs of each task. You can find the corresponding code [here](https://github.com/youngfish42/FMTL-Benchmark/blob/c70178a7022fd60202b3f4e178b7f347905d0cde/models/model.py#L250).
Feel free to let me know if there's anything else you'd like to know.

**Comment by Ultraman6** [comment] 2024-07-01 07:42
那请问我能否将其设置为任务独立的检测头？或者这样设置有没有必要？是否在实际训练过程中检测头：共享<=>独立？检测头是否和任务推理无关？仅仅只是对输出检测的类别通道？

**Comment by innovator-zero** [comment] 2024-07-06 08:03
Of course you can use a task-specific head for each task, which is a common setup in MTL methods and you could do experiments on it. In our method, the shared head outputs the maximum number of channels required among all training tasks. This operation is the same for both training and inference process.

**Comment by youngfish42** [comment] 2024-09-12 15:17
The problem discussed in this issue has been resolved via email, and the issue is temporarily closed.

(If you find that the problem is not resolved or there is further discussion, you are welcome to reopen the issue)

**Closed as completed by youngfish42** 2024-09-12 15:17 UTC
